name: Java CI with Maven

on:
  push:
    branches:
     - main
     - jenk
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
      with:
        ref: jenk
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        
    - name: Show Java version
      run: 'java -version'
      
    - name: Show directory
      run: 'pwd'

    - name: List files
      run: 'ls -al'

    - name: Install dependencies
      run: 'mvn compile'

    - name: Build application
      run: 'mvn package -DskipTests'

    - name: Test application
      run: 'mvn test'
